### ISSUE TITLE
Only manifest.txt files get downloaded, unsure if doing anything wrong.

### ISSUE THREAD

**Issue by xanek** [Expugn/priconne-image-extractor#2]
I copied the files from the github and extracted them to a folder, ran and updated the node and other python installs and then tried the "node app.js" but it gives this output in command prompt.

```
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/manifest_assetmanifest
update found: JP/unit2_assetmanifest
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/unit2_assetmanifest
starting deserialization process (this may take a really long time...)
```

and it immediately lets me type again so I am unsure if something went wrong?
Am I missing a step or have I misplaced the files from the github?
Or am I missing more files that were not included in this github?

This is what the folder looks like at the moment:
![image](https://github.com/Expugn/priconne-image-extractor/assets/23298441/79106e7e-d7ca-4425-a06a-15ef5c4d28a9)

**Comment by Expugn** [comment]
Did you change the `config.json` in any way?
It's possible that your current settings are trying to request for a file or files that don't exist.

Share your `config.json` if possible.

**Comment by xanek** [comment]
> Did you change the `config.json` in any way? It's possible that your current settings are trying to request for a file or files that don't exist.
> 
> Share your `config.json` if possible.

I left it as the default.
[config.json](https://github.com/Expugn/priconne-image-extractor/files/13459012/config.json)

**Comment by Expugn** [comment]
You can try changing `force_update.assets` to `true`:
```json
    "force_update": {
        "manifests": true,
        "assets": true
    },
```

If this wasn't your first time running `app.js`, maybe whatever contents you have in `manifest.json` is preventing new files from being re-downloaded

**Comment by xanek** [comment]
> If this wasn't your first time running `app.js`, maybe whatever contents you have in `manifest.json` is preventing new files from being re-downloaded

It was the first time running it.
also i'm getting this now when I run it after setting assets to true

```
E:\priconne\priconne-image-extractor-master>node app.js
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/manifest_assetmanifest
update found: JP/unit2_assetmanifest
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/unit2_assetmanifest
update found: JP/unit2_assetmanifest/unit_icon_unit_100731.unity3d
[dl_asset] http://prd-priconne-redive.akamaized.net/dl/pool/AssetBundles/7b/7bf5fbe7886468acc2f6a9ad94357bb0 -> unity3d\JP\unit2_assetmanifest\unit_icon_unit_100731.unity3d
starting deserialization process (this may take a really long time...)
E:\priconne\priconne-image-extractor-master\app.js:905
            if (err) throw err;
                     ^

PythonShellError: ModuleNotFoundError: No module named 'etcpak'
    at PythonShell.parseError (E:\priconne\priconne-image-extractor-master\node_modules\python-shell\index.js:295:21)
    at terminateIfNeeded (E:\priconne\priconne-image-extractor-master\node_modules\python-shell\index.js:190:32)
    at ChildProcess.<anonymous> (E:\priconne\priconne-image-extractor-master\node_modules\python-shell\index.js:182:13)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    ----- Python Traceback -----
    File "E:\priconne\priconne-image-extractor-master\deserialize.py", line 4, in <module>
      from vendor.UnityPy import UnityPy
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\__init__.py", line 3, in <module>
      from .environment import Environment
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\environment.py", line 6, in <module>
      from . import files
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\files\__init__.py", line 1, in <module>
      from .File import File, DirectoryInfo
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\files\File.py", line 163, in <module>
      from . import BundleFile, SerializedFile, WebFile, ObjectReader
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\files\SerializedFile.py", line 4, in <module>
      from . import File, ObjectReader
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\files\ObjectReader.py", line 4, in <module>
      from .. import classes
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\classes\__init__.py", line 7, in <module>
      from .AudioClip import AudioClip
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\classes\AudioClip.py", line 3, in <module>
      from ..export import AudioClipConverter
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\export\__init__.py", line 1, in <module>
      from . import MeshRendererExporter, SpriteHelper, Texture2DConverter, AudioClipConverter, MeshExporter
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\export\MeshRendererExporter.py", line 2, in <module>
      from ..classes import Renderer, SkinnedMeshRenderer, Material, Texture2D
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\classes\Texture2D.py", line 3, in <module>
      from ..export import Texture2DConverter
    File "E:\priconne\priconne-image-extractor-master\vendor\UnityPy\UnityPy\export\Texture2DConverter.py", line 2, in <module>
      import etcpak {
  traceback: 'Traceback (most recent call last):\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\deserialize.py", line 4, in <module>\r\n' +
    '    from vendor.UnityPy import UnityPy\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\__init__.py", line 3, in <module>\r\n' +
    '    from .environment import Environment\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\environment.py", line 6, in <module>\r\n' +
    '    from . import files\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\files\\__init__.py", line 1, in <module>\r\n' +
    '    from .File import File, DirectoryInfo\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\files\\File.py", line 163, in <module>\r\n' +
    '    from . import BundleFile, SerializedFile, WebFile, ObjectReader\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\files\\SerializedFile.py", line 4, in <module>\r\n' +
    '    from . import File, ObjectReader\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\files\\ObjectReader.py", line 4, in <module>\r\n' +
    '    from .. import classes\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\classes\\__init__.py", line 7, in <module>\r\n' +
    '    from .AudioClip import AudioClip\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\classes\\AudioClip.py", line 3, in <module>\r\n' +
    '    from ..export import AudioClipConverter\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\export\\__init__.py", line 1, in <module>\r\n' +
    '    from . import MeshRendererExporter, SpriteHelper, Texture2DConverter, AudioClipConverter, MeshExporter\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\export\\MeshRendererExporter.py", line 2, in <module>\r\n' +
    '    from ..classes import Renderer, SkinnedMeshRenderer, Material, Texture2D\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\classes\\Texture2D.py", line 3, in <module>\r\n' +
    '    from ..export import Texture2DConverter\r\n' +
    '  File "E:\\priconne\\priconne-image-extractor-master\\vendor\\UnityPy\\UnityPy\\export\\Texture2DConverter.py", line 2, in <module>\r\n' +
    '    import etcpak\r\n' +
    "ModuleNotFoundError: No module named 'etcpak'\r\n",
  executable: 'python',
  options: null,
  script: 'E:\\priconne\\priconne-image-extractor-master\\deserialize.py',
  args: [ 'unity3d\\JP\\unit2_assetmanifest\\unit_icon_unit_100731.unity3d' ],
  exitCode: 1
}
```

**Comment by Expugn** [comment]
Looks like `etcpak` is a dependency of UnityPy.
You can try running `pip install UnityPy==1.9.28` to install all the dependencies related to UnityPy

(`1.9.28` is an older version of UnityPy, I've had issues with later/the updated version. Also as a side note, I believe anything above Python 3.11 will break things, `Python v3.11.5` is the highest supported version I know of)

**Comment by xanek** [comment]
well got a different line ouputted now.
also im on 3.9.4 python

```
E:\priconne\priconne-image-extractor-master>node app.js
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/manifest_assetmanifest
update found: JP/unit2_assetmanifest
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/unit2_assetmanifest
update found: JP/unit2_assetmanifest/unit_icon_unit_100731.unity3d
[dl_asset] http://prd-priconne-redive.akamaized.net/dl/pool/AssetBundles/7b/7bf5fbe7886468acc2f6a9ad94357bb0 -> unity3d\JP\unit2_assetmanifest\unit_icon_unit_100731.unity3d
starting deserialization process (this may take a really long time...)
<DESERIALIZE> unity3d\JP\unit2_assetmanifest\unit_icon_unit_100731.unity3d -> image\JP\unit2_assetmanifest\unit_icon_unit_100731.png
```
It deserialized 1 thing and ended.

**Comment by Expugn** [comment]
If you check (a newly created `image` folder on same folder as `app.js`): `image/JP/unit2_assetmanifest/unit_icon_unit_100731.png`, you should hopefully see Miyako's unit icon with no issues.

The default `config.json` file is set to only download that 1 unit icon, if you want to download more files then you should edit your `config.json` to do so.

I believe to download ALL files (which will take a really long time and is probably a bad idea), you can edit your `config.json` to be:
```json
"JP": {
    "blacklist": {
        "manifests": [],
        "assets": []
    },
    "whitelist": {
        "manifests": [],
        "assets": []
    }
},
```

I'd recommend only downloading specific manifests that you're interested in.
You can check what manifests are available in `manifests/JP/manifest_assetmanifest.txt`
A couple examples:
- `all2_assetmanifest`: stuff like menu buttons
- `bg2_assetmanifest`: stuff like story backgrounds and full unit art
- `minigame2_assetmanifest`: stuff used in minigames, backgrounds/quiz images/etc
- `unit2_assetmanifest`: stuff like unit icons (e.g. the Miyako unit icon downloaded with default `config.json`)

**Comment by xanek** [comment]
So if I wanted to download things like event stuff, it would be the following correct?

```
        "JP": {
            "blacklist": {
                "manifests": [],
                "assets": []
            },
            "whitelist": {
                "manifests": [
                    "unit"
                ],
                "assets": [
                    "unit_icon_unit_100731"
                ]
            }
        },
```
If so, then it only gives this output and it immediately finishes

```
E:\priconne\priconne-image-extractor-master>node app.js
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/manifest_assetmanifest
update found: JP/unit2_assetmanifest
[dl_manifest] http://prd-priconne-redive.akamaized.net/dl/Resources/10052000/Jpn/AssetBundles/Windows/manifest/unit2_assetmanifest
starting deserialization process (this may take a really long time...)

E:\priconne\priconne-image-extractor-master>
```

**Comment by xanek** [comment]
So how exactly do I know what specific assets I can download for the whitelist?

Like for example if I just wanted to download event assets and new character artwork, like the full body artwork or the sprite sheet I guess(?), how would it look?

I currently have just this for the event assets, if this is correct?

```json
        "JP": {
            "blacklist": {
                "manifests": [],
                "assets": []
            },
            "whitelist": {
                "manifests": [
                    "event2_assetmanifest"
                ],
                "assets": [
                    
                ]
            }
        },
```
I'm a bit confused where you are able to find the list of specific assets to download other than downloading everything from the manifest.

Also, if you do the download once, does it keep track of what you already downloaded if the manifests update or do you have to redownload everything?

**Comment by Expugn** [comment]
> So how exactly do I know what specific assets I can download for the whitelist?

Check the manifest text files

> Like for example if I just wanted to download event assets and new character artwork, like the full body artwork or the sprite sheet I guess(?), how would it look?

what you have works but you can also do
```json
        "JP": {
            "blacklist": {
                "manifests": [],
                "assets": []
            },
            "whitelist": {
                "manifests": [
                    "event",
                    "bg"
                ],
                "assets": []
            }
        },
```

> I'm a bit confused where you are able to find the list of specific assets to download other than downloading everything from the manifest.

You'd have to check the manifest folder text files. Run the script once and CTRL+C to quickly stop it when its starting to download files so you can get the manifest without downloading everything.

 > Also, if you do the download once, does it keep track of what you already downloaded if the manifests update or do you have to redownload everything?

In theory it should, file versions are saved in `manifest.json`, but i never really fully tested the feature so if might be bugged. Make sure `force_update.assets` is set back to `false`

**Comment by xanek** [comment]
> what you have works but you can also do
> 
> ```json
>         "JP": {
>             "blacklist": {
>                 "manifests": [],
>                 "assets": []
>             },
>             "whitelist": {
>                 "manifests": [
>                     "event",
>                     "bg"
>                 ],
>                 "assets": []
>             }
>         },
> ```
> 

Are those 2 that you listed just basically the same thing as the event2_assetmanifest.txt & bg2_assetmanifest.txt just accepted in a shorter form?
 
> You'd have to check the manifest folder text files. Run the script once and CTRL+C to quickly stop it when its starting to download files so you can get the manifest without downloading everything.

Looking at the event2_assetmanifest.txt, so like if I wanted to specifically download like event teasers, would I put in like this or would it be incorrect?
```json
         "JP": {
             "blacklist": {
                 "manifests": [],
                 "assets": []
             },
             "whitelist": {
                 "manifests": [
                     "event",
                     "bg"
                 ],
                 "assets": [event_teaser_]
             }
         },
```
And would it only just do the event teasers when I do it like this or would it do the event teaserse + backgrounds that I didn't specifically note?

> In theory it should, file versions are saved in `manifest.json`, but i never really fully tested the feature so if might be bugged. Make sure `force_update.assets` is set back to `false`

Is the force_update.assets in the config.json under
```json
    "force_update": {
        "manifests": true,
        "assets": true
    },
```
or in a different file?

**Comment by Expugn** [comment]
> Are those 2 that you listed just basically the same thing as the event2_assetmanifest.txt & bg2_assetmanifest.txt just accepted in a shorter form?

Basically, the script just looks for substrings that match in file name.

> Looking at the event2_assetmanifest.txt, so like if I wanted to specifically download like event teasers, would I put in like this or would it be incorrect?

add double quotes, `"event_teaser_"`

although, im not really familiar with event teasers so if they arent Texture2D files then this script might not be able to deserialize it properly.

> And would it only just do the event teasers when I do it like this or would it do the event teaserse + backgrounds that I didn't specifically note?

it will only download event teasers. youll need to look through the bg manifest to pick out what youre interested in

> Is the force_update.assets in the config.json under

yes thats correct, in the `config.json`

**Comment by xanek** [comment]
> > Looking at the event2_assetmanifest.txt, so like if I wanted to specifically download like event teasers, would I put in like this or would it be incorrect?
> 
> add double quotes, `"event_teaser_"`

So adding in the double quotes to the assets that are just part of the file name will just download everything that includes that portion of the file name correct?
And yeah, the event_teasers are texture2d files.

Otherwise then, well I think that pretty much covers what I currently have for questions in regards to all of this, not sure if I'll have questions once the new update drops, but I was primarily looking for the things I have noted.

**Comment by xanek** [comment]
> > Looking at the event2_assetmanifest.txt, so like if I wanted to specifically download like event teasers, would I put in like this or would it be incorrect?
> 
> add double quotes, `"event_teaser_"`

So adding in the double quotes to the assets that are just part of the file name will just download everything that includes that portion of the file name correct?
And yeah, the event_teasers are texture2d files.

Would I need to turn both manifest and assets in the config.json to false in order for it to download new files when they become available, or does only one of them need to be set to false?

Otherwise then, well I think that pretty much covers what I currently have for questions in regards to all of this, not sure if I'll have questions once the new update drops, but I was primarily looking for the things I have noted.

**Comment by Expugn** [comment]
> So adding in the double quotes to the assets that are just part of the file name will just download everything that includes that portion of the file name correct?

adding double quotes like that just fixes the invalid `json` format you had earlier
```
[ event_teaser_ ]
```
is invalid json

> Would I need to turn both manifest and assets in the config.json to false in order for it to download new files when they become available, or does only one of them need to be set to false?

keep manifest as `true`, asset can be set to true/false depending on if you want to force the download of files or not

**Comment by xanek** [comment]
> adding double quotes like that just fixes the invalid `json` format you had earlier
> 
> ```
> [ event_teaser_ ]
> ```
> 
> is invalid json

I understand that, but after putting in the double quotes, it'll just download all the files that start with event_teaser_ correct?

**Comment by Expugn** [comment]
> I understand that, but after putting in the double quotes, it'll just download all the files that start with event_teaser_ correct?

yes in theory thats correct
